interface ZIF_CDS_I_ACCOUNTS_VGN_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
 CREATE_ZCDS_I_ACCOUNTS_VGN     TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F791D756',
 DELETE_ZCDS_I_ACCOUNTS_VGN     TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F7925756',
 LOCK_ZCDS_I_ACCOUNTS_VGN       TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F7911756',
 SAVE_ZCDS_I_ACCOUNTS_VGN       TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F792D756',
 UNLOCK_ZCDS_I_ACCOUNTS_VGN     TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F7915756',
 UPDATE_ZCDS_I_ACCOUNTS_VGN     TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F7921756',
 VALIDATE_ZCDS_I_ACCOUNTS_VGN   TYPE /BOBF/ACT_KEY VALUE '080027BB14751EEAB78F93F9F7929756',
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_I_ACCOUNTS_VGN,
        BEGIN OF LOCK_ZCDS_I_ACCOUNTS_VGN,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZCDS_I_ACCOUNTS_VGN,
        BEGIN OF UNLOCK_ZCDS_I_ACCOUNTS_VGN,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZCDS_I_ACCOUNTS_VGN,
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '080027BB14751EEAB78F94F6A919D756',
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F790F756',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F790B756',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F791B756',
      END OF ZCDS_I_ACCOUNTS_VGN,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F7933756',
      END OF ZCDS_I_ACCOUNTS_VGN_LOCK,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F7931756',
      END OF ZCDS_I_ACCOUNTS_VGN_MESSAGE,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '080027BB14751EEAB78F93F9F7935756',
      END OF ZCDS_I_ACCOUNTS_VGN_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '080027BB14751EEAB78F939581E89756' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_I_ACCOUNTS_VGN' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '080027BB14751EEAB78F94F6A919F756',
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_I_ACCOUNTS_VGN            TYPE /BOBF/OBM_NODE_KEY VALUE '080027BB14751EEAB78F93D3BFB67756',
 ZCDS_I_ACCOUNTS_VGN_LOCK       TYPE /BOBF/OBM_NODE_KEY VALUE '080027BB14751EEAB78F93F9F790D756',
 ZCDS_I_ACCOUNTS_VGN_MESSAGE    TYPE /BOBF/OBM_NODE_KEY VALUE '080027BB14751EEAB78F93F9F7909756',
 ZCDS_I_ACCOUNTS_VGN_PROPERTY   TYPE /BOBF/OBM_NODE_KEY VALUE '080027BB14751EEAB78F93F9F7919756',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ACCOUNT_NUMBER                 TYPE STRING VALUE 'ACCOUNT_NUMBER',
  BANK_NAME                      TYPE STRING VALUE 'BANK_NAME',
  CITY                           TYPE STRING VALUE 'CITY',
  BALANCE                        TYPE STRING VALUE 'BALANCE',
  ACCOUNT_CATEGORY               TYPE STRING VALUE 'ACCOUNT_CATEGORY',
  LASTCHANGEDAT                  TYPE STRING VALUE 'LASTCHANGEDAT',
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_I_ACCOUNTS_VGN,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '080027BB14751EEAB78F93D3BFB69756',
      END OF ZCDS_I_ACCOUNTS_VGN,
    END OF SC_NODE_CATEGORY .
endinterface.
